import { FC, Suspense, useEffect, useState } from 'react'
import { useTranslation } from 'react-i18next'
import { Button } from 'shared/ui'

interface ErrorButtonProps {
  className?: string
}

export const ErrorButton: FC<ErrorButtonProps> = (props) => {
  const { className } = props
  const { t } = useTranslation()

  const [error, setError] = useState(false)

  const onThrowError = () => {
    setError(true)
  }

  useEffect(() => {
    if (error) {
      throw new Error('Error generated by ErrorButton')
    }
  }, [error])

  return (
    <Suspense fallback="">
      <Button title={t('throw-error')} onClick={onThrowError} />
    </Suspense>
  )
}
