export enum ProfileFormFieldErrorCode {
  NO_USER_DATA = 'NO_USER_DATA',
  INCORRECT_USER_DATA = 'INCORRECT_USER_DATA',
  INCORRECT_USER_AGE = 'INCORRECT_USER_AGE',
  SERVER_ERROR = 'SERVER_ERROR',
}
